#!/bin/bash

echo "🔧 Fixing Git History - Removing Large Files"
echo ""
echo "Option 1: Fresh Start (RECOMMENDED)"
echo "=================================="
echo "# 1. Remove .git directory"
echo "rm -rf .git"
echo ""
echo "# 2. Initialize fresh repo"
echo "git init"
echo "git add ."
echo "git commit -m 'Initial commit: ParallaxPay clean version'"
echo ""
echo "# 3. Force push to GitHub"
echo "git branch -M main"
echo "git remote add origin https://github.com/shariqazeem/parallaxpay.git"
echo "git push -f -u origin main"
echo ""
echo "This will give you a clean history with only the current files (~10MB)"
echo ""
echo "=========================================="
echo "Option 2: Clean History (Advanced)"
echo "=========================================="
echo "Use git filter-branch or BFG Repo-Cleaner to remove large files from history"
echo "This is more complex and takes longer"
echo ""
echo "Which option do you prefer?"
